# Generated by Django 3.2.4 on 2021-06-18 23:15

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='topic', unique=True),
            preserve_default=False,
        ),
    ]
